# Generated by Django 5.2.4 on 2025-08-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='comments',
            new_name='comments_count',
        ),
    ]
